In [1]:
import numpy as np

x = np.array([[0., 1., ],
              [2., 3.],
              [4., 5.]])
print(x.shape)

(3, 2)


In [23]:
x = x.reshape((6, 1))
print(x)
x = x.reshape((2, 3))
print(x)

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[[0. 1. 2.]
 [3. 4. 5.]]


In [26]:
import numpy as np

a = np.array([0.5, 1.])
b = np.array([1, 0.25])
c = a + b
print(c)

[1.5  1.25]
